trigger:
  branches:
    include:
      - main

variables:
  - group: consultants-secrets
  - name: acrName
    value: consultantsregistry
  - name: backendImage
    value: consultants-backend
  - name: frontendImage
    value: consultants-frontend
  - name: tag
    value: $(Build.BuildId)
  - name: JAVA_HOME
    value: 'C:\Users\Antoine\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.18.8-hotspot'
  - name: PATH
    value: '$(JAVA_HOME)\bin;$(PATH)'

stages:
  - stage: Build
    displayName: '1 - Build'
    jobs:
      - job: BuildJob
        pool:
          name: Default
        steps:
          - checkout: self

          - script: |
              "C:\Users\Antoine\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.18.8-hotspot\bin\java" -version
              SET JAVA_HOME=C:\Users\Antoine\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.18.8-hotspot
              SET PATH=C:\Users\Antoine\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.18.8-hotspot\bin;C:\Windows\System32;C:\Windows
              mvnw.cmd compile
            displayName: 'Maven Compile'

          - script: |
              set JAVA_HOME=C:\Users\Antoine\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.18.8-hotspot
              set PATH=%JAVA_HOME%\bin;%PATH%
              cd consultants-frontend
              npm install
              npm run build
            displayName: 'React Build'

  - stage: Tests
    displayName: '2 - Tests'
    dependsOn: Build
    jobs:
      - job: TestJob
        pool:
          name: Default
        steps:
          - checkout: self

          - script: |
              "C:\Users\Antoine\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.18.8-hotspot\bin\java" -version
              SET JAVA_HOME=C:\Users\Antoine\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.18.8-hotspot
              SET PATH=C:\Users\Antoine\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.18.8-hotspot\bin;C:\Windows\System32;C:\Windows
              mvnw.cmd verify
            displayName: 'Run Tests'
